name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
      
    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1
      env:
        GOROOT: ""
      with:
        # golangci-lint docker release tag
        golangci_lint_version: 1.23 # optional, default is v1.23. Setting this follows guidance to not "break" all builds by blanket default change.
        args: "run -E misspell -v"
        
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Run Gosec Security Scanner
      run:  |
                export PATH=$PATH:$(go env GOPATH)/bin
                go get github.com/securego/gosec/cmd/gosec
                gosec ./...
